import Link from "next/link";
import {redirect} from "next/navigation";
import {ArrowLeft,ClipboardList} from "lucide-react";
import {createClient} from "@/lib/supabase/server";
import {getTeacherEducationTarget} from "@/lib/teacher-education-context";
import {ActivityForm} from "@/features/question-bank/activity-form";

export default async function AssignmentsPage({searchParams}:{searchParams:Promise<{created?:string;error?:string}>}){
 const query=await searchParams,s=await createClient("teacher"),{data:{user}}=await s.auth.getUser();if(!user)redirect("/auth/teacher/login");const target=await getTeacherEducationTarget();if(!target)redirect("/teacher/dashboard?error=environment-required");if(target.educationSystem!=="american")redirect("/teacher/question-bank");
 const {data:unitId,error:unitError}=await s.rpc("get_or_create_american_assignment_unit",{p_category:target.americanCategory});if(unitError||!unitId)redirect("/teacher/dashboard?error=assignments");
 const [{data:questions},{data:modules}]=await Promise.all([s.from("question_bank_questions").select("id,text,points,position").eq("unit_id",unitId).order("position"),s.from("exams").select("id,title,status,created_at,exam_assignments(id,exam_attempts(id,status,score))").eq("teacher_id",user.id).eq("education_system","american").eq("american_category",target.americanCategory).in("kind",["self_practice","homework"]).order("created_at",{ascending:false})]);
 return <main className="app-content question-bank-page"><Link className="back-link" href="/teacher/dashboard"><ArrowLeft/>Back to dashboard</Link><header><div><small>American · {target.americanCategory.toUpperCase()}</small><h1>Assignments</h1><p>Create and manage assignments directly. No Units or grouping.</p></div></header>{query.created&&<p className="form-success">Assignment added successfully.</p>}{query.error&&<p className="form-error">Check the assignment questions and correct answers.</p>}<section className="panel teacher-activity-create"><h2>Add Assignment</h2><ActivityForm unitId={unitId} oldQuestions={(questions??[]).map(q=>({id:q.id,text:q.text,points:Number(q.points)}))} initialKind="self_practice" assignmentMode/></section><section className="panel section-list"><div className="panel-head"><div><h2>Available assignments</h2><p>{modules?.length??0} assignments</p></div></div>{(modules??[]).map(module=>{const attempts=module.exam_assignments.flatMap(a=>a.exam_attempts),submitted=attempts.filter(a=>a.status!=="in_progress");return <article className="activity" key={module.id}><span className="activity-icon"><ClipboardList/></span><div><b>{module.title}</b><small>{submitted.length} of {module.exam_assignments.length} students submitted</small></div><Link className="button secondary small" href={`/teacher/exams/${module.id}/results`}>Students & scores</Link></article>})}{!modules?.length&&<div className="empty-state"><ClipboardList/><h2>No assignments yet</h2><p>Add the first assignment above.</p></div>}</section></main>;
}
