import {z} from "zod";
export const EDUCATION_SYSTEMS=[{value:"american",label:"American"},{value:"national",label:"National"}] as const;
export const AMERICAN_CATEGORIES=[{value:"classified",label:"Classified"},{value:"sat",label:"SAT"},{value:"est",label:"EST"}] as const;
export const NATIONAL_GRADES=[{value:"sensor_1",label:"Senior 1"},{value:"sensor_2",label:"Senior 2"},{value:"sensor_3",label:"Senior 3"}] as const;
export type EducationSystem=(typeof EDUCATION_SYSTEMS)[number]["value"];export type AmericanCategory=(typeof AMERICAN_CATEGORIES)[number]["value"];export type NationalGrade=(typeof NATIONAL_GRADES)[number]["value"];
export type EducationTarget={educationSystem:"american";americanCategory:AmericanCategory;nationalGrade:null}|{educationSystem:"national";americanCategory:null;nationalGrade:NationalGrade};
export const educationTargetSchema=z.object({educationSystem:z.enum(["american","national"],{error:"Please select an educational system."}),americanCategory:z.union([z.enum(["classified","sat","est"]),z.null()]),nationalGrade:z.union([z.enum(["sensor_1","sensor_2","sensor_3"]),z.null()])}).superRefine((v,c)=>{if(v.educationSystem==="american"&&!v.americanCategory)c.addIssue({code:"custom",path:["americanCategory"],message:"Please select an American category."});if(v.educationSystem==="american"&&v.nationalGrade!==null)c.addIssue({code:"custom",path:["nationalGrade"],message:"American content cannot have a National grade."});if(v.educationSystem==="national"&&v.americanCategory!==null)c.addIssue({code:"custom",path:["americanCategory"],message:"National content cannot have an American category."});if(v.educationSystem==="national"&&v.nationalGrade===null)c.addIssue({code:"custom",path:["nationalGrade"],message:"Please select a National grade."})});
export function parseEducationTarget(v:{educationSystem:unknown;americanCategory?:unknown;nationalGrade:unknown}){return educationTargetSchema.safeParse({educationSystem:v.educationSystem,americanCategory:v.americanCategory||null,nationalGrade:v.nationalGrade||null})}
export function educationSystemLabel(v:unknown){return EDUCATION_SYSTEMS.find(x=>x.value===v)?.label??"Needs classification"}export function americanCategoryLabel(v:unknown){return AMERICAN_CATEGORIES.find(x=>x.value===v)?.label??null}export function nationalGradeLabel(v:unknown){return NATIONAL_GRADES.find(x=>x.value===v)?.label??null}
