-- Intentionally contains no application-user records.
--
-- A profile ID must always reference a real auth.users ID. Create the first
-- administrator through Supabase Authentication, copy that user's UUID, and
-- then run the bootstrap statement documented in README.md.
--
-- Never insert placeholder UUIDs into public.profiles and never create
-- production users with shared seed credentials.
