import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, GraduationCap } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { createTeacher } from "@/features/teachers/actions";

export default async function NewTeacherPage(){
 const supabase=await createClient(),{data:{user}}=await supabase.auth.getUser(); if(!user)redirect("/auth/admin/login");
 const {data:profile}=await supabase.from("profiles").select("role").eq("id",user.id).single(); if(profile?.role!=="admin")redirect("/");
 return <main className="app-frame"><aside><Link href="/" className="brand"><span className="brand-mark"><GraduationCap/></span>Academy</Link><nav><Link className="active" href="/admin/teachers">Teachers</Link><Link href="/admin/dashboard">Dashboard</Link></nav></aside><section className="app-content form-page"><Link className="back-link" href="/admin/teachers"><ArrowLeft size={16}/> Back to teachers</Link><header><div><small>Admin workspace</small><h1>Add teacher</h1><p>Create an independent login account and teacher profile.</p></div></header><form action={createTeacher} className="panel teacher-form"><div className="form-grid"><div className="field"><label htmlFor="displayName">Display name</label><input id="displayName" name="displayName" minLength={3} maxLength={120} required/></div><div className="field"><label htmlFor="email">Email address</label><input id="email" name="email" type="email" autoComplete="off" required/></div><div className="field"><label htmlFor="password">Temporary password</label><input id="password" name="password" type="password" minLength={8} maxLength={72} autoComplete="new-password" required/><small>Give this password securely to the teacher.</small></div><div className="field"><label htmlFor="imageUrl">Profile image URL</label><input id="imageUrl" name="imageUrl" type="url" placeholder="https://…" /></div><div className="field full"><label htmlFor="biography">Biography</label><textarea id="biography" name="biography" maxLength={1000} rows={5}/></div><label className="check full"><input type="checkbox" name="isActive" defaultChecked/><span><b>Active teacher</b><small>Students can browse this teacher and access assigned content.</small></span></label></div><div className="form-actions"><Link className="button secondary" href="/admin/teachers">Cancel</Link><button className="button" type="submit">Create teacher</button></div></form></section></main>
}
