import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft, Shuffle } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { createRandomPastExam } from "@/features/exams/actions";

const messages:Record<string,string>={invalid:"Check all exam settings and select at least one student.",questions:"There are not enough old questions for the requested exam size.",create:"The random exam could not be created."};
export default async function RandomExamPage({searchParams}:{searchParams:Promise<{error?:string}>}){
 const query=await searchParams,supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/auth/teacher/login");
 const [{data:enrollments},{count:questionCount},{data:sources}]=await Promise.all([
  supabase.from("teacher_student_enrollments").select("student_id").eq("teacher_id",user.id).eq("status","active").or(`access_expires_at.is.null,access_expires_at.gt.${new Date().toISOString()}`),
  supabase.from("questions").select("id,exams!inner(teacher_id,kind)",{count:"exact",head:true}).eq("exams.teacher_id",user.id).eq("exams.kind","standard"),
  supabase.from("exams").select("id").eq("teacher_id",user.id).eq("kind","standard"),
 ]);
 const ids=(enrollments??[]).map(row=>row.student_id),{data:profiles}=ids.length?await supabase.from("profiles").select("id,full_name").in("id",ids):{data:[]};
 return <main className="app-content exam-page"><Link className="back-link" href="/teacher/exams"><ArrowLeft/>Back to exams</Link><header><div><small>Teacher workspace</small><h1>Random exam from past exams</h1><p>The system balances questions across {sources?.length??0} source exams and weights selection by question points.</p></div></header>{query.error&&<p className="form-error">{messages[query.error]??messages.create}</p>}<form action={createRandomPastExam} className="panel teacher-form"><div className="form-grid"><div className="field"><label>Title</label><input name="title" required minLength={3}/></div><div className="field"><label>Number of questions</label><input name="questionCount" type="number" min={1} max={Math.max(1,questionCount??1)} defaultValue={Math.min(20,questionCount??1)} required/><small>{questionCount??0} old questions available</small></div><div className="field"><label>Duration (minutes)</label><input name="durationMinutes" type="number" min={1} max={600} defaultValue={30} required/></div><div className="field"><label>Maximum attempts</label><input name="maxAttempts" type="number" min={1} max={20} defaultValue={1} required/></div><div className="field full"><label>Description</label><textarea name="description" rows={3}/></div><div className="field full"><label>Instructions</label><textarea name="instructions" rows={3}/></div><div className="field"><label>Starts at</label><input name="startsAt" type="datetime-local"/></div><div className="field"><label>Ends at</label><input name="endsAt" type="datetime-local"/></div><div className="field"><label>Passing score</label><input name="passingScore" type="number" min={0} step=".01"/></div><label className="check full"><input name="assignAll" type="checkbox" defaultChecked/><span><b>Assign to all active students</b></span></label><div className="student-selector full">{(profiles??[]).map(profile=><label key={profile.id}><input name="studentIds" type="checkbox" value={profile.id}/>{profile.full_name}</label>)}</div></div><div className="form-actions"><Link className="button secondary" href="/teacher/exams">Cancel</Link><button className="button" disabled={!questionCount}><Shuffle size={18}/>Generate and publish</button></div></form></main>;
}
