"use client";
import {useState} from "react";
import {BookOpen,ClipboardCheck,Plus,Trash2,X} from "lucide-react";
import {createActivityWithUploadedQuestions as createActivityWithQuestions} from "./image-actions";
import {QuestionImageUpload} from "@/components/question-image-upload";
type Kind="self_practice"|"homework";type OldQuestion={id:string;text:string;points:number};type Choice={text:string;isCorrect:boolean};type NewQuestion={text:string;imageUrl:string;points:number;choices:Choice[]};
const blank=():NewQuestion=>({text:"",imageUrl:"",points:1,choices:[{text:"",isCorrect:true},{text:"",isCorrect:false}]});
export function ActivityForm({unitId,oldQuestions,initialKind=null}:{unitId:string;oldQuestions:OldQuestion[];initialKind?:Kind|null}){
 const [kind,setKind]=useState<Kind|null>(initialKind),[selected,setSelected]=useState<string[]>([]),[questions,setQuestions]=useState<NewQuestion[]>([]);
 if(!kind)return <div className="activity-kind-actions"><button className="activity-kind-card" type="button" onClick={()=>setKind("self_practice")}><BookOpen/><span><b>Create Self Practice</b><small>Untimed and without a deadline</small></span></button><button className="activity-kind-card homework" type="button" onClick={()=>setKind("homework")}><ClipboardCheck/><span><b>Create Homework</b><small>Untimed with a submission deadline</small></span></button></div>;
 const homework=kind==="homework";
 return <form action={createActivityWithQuestions} className="activity-builder" onSubmit={e=>{const f=new FormData(e.currentTarget);(e.currentTarget.elements.namedItem("payload") as HTMLInputElement).value=JSON.stringify({unitId,kind,title:f.get("title"),deadline:f.get("deadline")||null,assignAll:f.get("assignAll")==="on",questionIds:selected,newQuestions:questions})}}>
  <input type="hidden" name="payload"/><div className="activity-form-title"><div><b>{homework?"Create Homework":"Create Self Practice"}</b><small>Select old questions and/or create new questions below.</small></div>{!initialKind&&<button type="button" className="text-action" onClick={()=>setKind(null)}><X/>Cancel</button>}</div>
  <div className="form-grid"><div className="field"><label>Title</label><input name="title" required/></div>{homework&&<div className="field"><label>Submission deadline</label><input name="deadline" type="datetime-local" required/></div>}</div>
  <section className="activity-question-source"><h3>Choose from old questions</h3>{oldQuestions.length?<div className="old-question-picker">{oldQuestions.map(q=><label key={q.id}><input type="checkbox" checked={selected.includes(q.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,q.id]:v.filter(id=>id!==q.id))}/><span><b>{q.text}</b><small>{q.points} points</small></span></label>)}</div>:<p>No old questions in this Unit yet. Create questions below.</p>}</section>
  <section className="activity-new-questions"><div className="panel-head"><div><h3>Create new questions</h3><p>New questions are saved to this Unit for future activities.</p></div><button type="button" className="button secondary small" onClick={()=>setQuestions(v=>[...v,blank()])}><Plus/>New question</button></div>
   {questions.map((q,qi)=><article className="question-editor" key={qi}><div className="question-top"><b>New question {qi+1}</b><button type="button" onClick={()=>setQuestions(v=>v.filter((_,i)=>i!==qi))}><Trash2/></button></div><div className="field"><label>Question text</label><textarea value={q.text} onChange={e=>setQuestions(v=>v.map((x,i)=>i===qi?{...x,text:e.target.value}:x))} required/></div><div className="form-grid"><QuestionImageUpload value={q.imageUrl} fileName={`newQuestionImage_${qi}`} onChange={imageUrl=>setQuestions(v=>v.map((x,i)=>i===qi?{...x,imageUrl}:x))}/><div className="field"><label>Points</label><input type="number" min=".01" step=".01" value={q.points} onChange={e=>setQuestions(v=>v.map((x,i)=>i===qi?{...x,points:Number(e.target.value)}:x))}/></div></div>
    {q.choices.map((c,ci)=><div className="choice-row" key={ci}><input value={c.text} onChange={e=>setQuestions(v=>v.map((x,i)=>i===qi?{...x,choices:x.choices.map((choice,j)=>j===ci?{...choice,text:e.target.value}:choice)}:x))} placeholder={`Choice ${ci+1}`} required/><label><input type="checkbox" checked={c.isCorrect} onChange={e=>setQuestions(v=>v.map((x,i)=>i===qi?{...x,choices:x.choices.map((choice,j)=>j===ci?{...choice,isCorrect:e.target.checked}:choice)}:x))}/>Correct</label>{q.choices.length>2&&<button type="button" onClick={()=>setQuestions(v=>v.map((x,i)=>i===qi?{...x,choices:x.choices.filter((_,j)=>j!==ci)}:x))}><Trash2/></button>}</div>)}
    <button type="button" className="text-action" onClick={()=>setQuestions(v=>v.map((x,i)=>i===qi?{...x,choices:[...x.choices,{text:"",isCorrect:false}]}:x))}><Plus/>Add choice</button></article>)}
  </section><label className="check"><input name="assignAll" type="checkbox" defaultChecked/>Assign all matching students</label><button className="button">{homework?"Create Homework":"Create Self Practice"}</button>
 </form>
}
