import Link from "next/link";
import {redirect} from "next/navigation";
import {ArrowLeft} from "lucide-react";
import {createClient} from "@/lib/supabase/server";
import {requireTeacherEducationTarget} from "@/lib/teacher-education-context";
import {getTeacherMaterialStudents} from "@/lib/teacher-material-students";
import {MaterialForm} from "@/features/materials/material-form";

function local(value:string|null){if(!value)return "";const d=new Date(value),pad=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
export default async function Page({params,searchParams}:{params:Promise<{materialId:string}>;searchParams:Promise<{error?:string}>}){const {materialId}=await params,query=await searchParams,s=await createClient(),{data:{user}}=await s.auth.getUser();if(!user)redirect("/auth/teacher/login");const target=await requireTeacherEducationTarget();let request=s.from("materials").select("id,title,description,material_type,external_drive_url,cover_image_url,available_from,available_until,status").eq("id",materialId).eq("teacher_id",user.id).eq("resource_kind","study_note").eq("education_system",target.educationSystem);request=target.educationSystem==="american"?request.eq("american_category",target.americanCategory):request.eq("national_grade",target.nationalGrade);const [{data:material},{data:assignments},students]=await Promise.all([request.single(),s.from("material_assignments").select("student_id,revoked_at").eq("material_id",materialId),getTeacherMaterialStudents()]);if(!material)redirect("/teacher/study-notes");return <main className="app-content exam-page"><Link className="back-link" href="/teacher/study-notes"><ArrowLeft/>Back to Study Notes</Link><header><h1>Edit Study Note</h1><p>Update the resource and student access.</p></header>{query.error&&<p className="form-error">The study note could not be updated. Check the fields and try again.</p>}<MaterialForm kind="study_note" students={students} initial={{id:material.id,title:material.title,description:material.description,materialType:material.material_type,externalUrl:material.external_drive_url,coverImageUrl:material.cover_image_url,availableFrom:local(material.available_from),availableUntil:local(material.available_until),published:material.status==="published",studentIds:(assignments??[]).filter(a=>!a.revoked_at).map(a=>a.student_id)}}/></main>}
