import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { createLessonVideo } from "@/features/videos/actions";
const errors:Record<string,string>={invalid:"Check all video and availability fields.",youtube:"Enter a valid YouTube watch, Shorts, embed, or youtu.be link.",create:"The lesson video could not be created.",assign:"The video could not be assigned to the selected students."};
export default async function Page({searchParams}:{searchParams:Promise<{error?:string}>}){
 const query=await searchParams,supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/auth/teacher/login");
 const {data:enrollments}=await supabase.from("teacher_student_enrollments").select("student_id").eq("teacher_id",user.id).eq("status","active");
 const ids=(enrollments??[]).map(e=>e.student_id),{data:students}=ids.length?await supabase.from("profiles").select("id,full_name").in("id",ids):{data:[]};
 return <main className="app-content exam-page"><Link className="back-link" href="/teacher/videos"><ArrowLeft size={16}/>Back to lesson videos</Link><header><div><small>Teacher workspace</small><h1>Add lesson video</h1><p>Publish a protected YouTube lesson and assign it to your students.</p></div></header>{query.error&&<p className="form-error">{errors[query.error]??errors.create}</p>}<form action={createLessonVideo} className="panel teacher-form"><div className="form-grid"><div className="field"><label>Title</label><input name="title" minLength={3} maxLength={200} required/></div><div className="field"><label>YouTube URL</label><input name="youtubeUrl" type="url" placeholder="https://youtube.com/watch?v=…" required/></div><div className="field full"><label>Description</label><textarea name="description" maxLength={2000} rows={4}/></div><div className="field"><label>Lesson name</label><input name="lessonName" maxLength={200}/></div><div className="field"><label>Category</label><input name="categoryName" maxLength={200}/></div><div className="field"><label>Available from</label><input name="availableFrom" type="datetime-local"/></div><div className="field"><label>Available until</label><input name="availableUntil" type="datetime-local"/></div><div className="field"><label>Maximum views</label><input name="maxViews" type="number" min={1} placeholder="Unlimited"/></div><label className="check"><input name="publish" type="checkbox" defaultChecked/><span><b>Publish now</b></span></label><label className="check full"><input name="assignAll" type="checkbox" defaultChecked/><span><b>Assign to all active students</b></span></label><div className="student-selector full"><small>Or select students when “Assign all” is unchecked:</small>{(students??[]).map(s=><label key={s.id}><input type="checkbox" name="studentIds" value={s.id}/>{s.full_name}</label>)}{!students?.length&&<small>No active students are enrolled.</small>}</div></div><div className="form-actions"><Link className="button secondary" href="/teacher/videos">Cancel</Link><button className="button">Create video</button></div></form></main>;
}
