"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import { requireTeacherEducationTarget } from "@/lib/teacher-education-context";
const schema=z.object({contentKind:z.enum(["material_book","study_note"]),educationSystem:z.enum(["american","national"]),americanCategory:z.enum(["classified","sat","est"]).nullable(),nationalGrade:z.enum(["sensor_1","sensor_2","sensor_3"]).nullable(),title:z.string().trim().min(3).max(200),description:z.string().trim().max(2000),materialType:z.string().trim().min(2).max(80),externalUrl:z.string().url().refine(v=>v.startsWith("https://")),coverImageUrl:z.union([z.literal(""),z.string().url().refine(v=>v.startsWith("https://"))]),availableFrom:z.string(),availableUntil:z.string(),publish:z.string().optional(),assignAll:z.string().optional(),studentIds:z.array(z.string().uuid())}).refine(v=>(v.educationSystem==="american"&&v.americanCategory!==null&&v.nationalGrade===null)||(v.educationSystem==="national"&&v.americanCategory===null&&v.nationalGrade!==null)).refine(v=>!v.availableFrom||!v.availableUntil||Date.parse(v.availableUntil)>Date.parse(v.availableFrom));
export async function createMaterialBook(formData:FormData){
 const supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/auth/teacher/login");
 const target=await requireTeacherEducationTarget(),parsed=schema.safeParse({...Object.fromEntries(formData),contentKind:formData.get("contentKind")||"material_book",...target,studentIds:formData.getAll("studentIds").map(String)});if(!parsed.success)redirect(`/teacher/${formData.get("contentKind")==="study_note"?"study-notes":"materials"}/new?error=invalid`);const input=parsed.data,section=input.contentKind==="study_note"?"study-notes":"materials";
 const {data:material,error}=await supabase.from("materials").insert({teacher_id:user.id,resource_kind:input.contentKind,education_system:input.educationSystem,american_category:input.americanCategory,national_grade:input.nationalGrade,title:input.title,description:input.description||null,material_type:input.materialType,external_drive_url:input.externalUrl,storage_path:null,cover_image_url:input.coverImageUrl||null,available_from:input.availableFrom?new Date(input.availableFrom).toISOString():null,available_until:input.availableUntil?new Date(input.availableUntil).toISOString():null,status:input.publish==="on"?"published":"draft"}).select("id").single();
 if(error||!material)redirect(`/teacher/${section}/new?error=create`);
 if(input.publish==="on"){let ids=input.studentIds;if(input.assignAll==="on"){const {data:e}=await supabase.from("teacher_student_enrollments").select("student_id").eq("teacher_id",user.id).eq("status","active").or(`access_expires_at.is.null,access_expires_at.gt.${new Date().toISOString()}`);ids=(e??[]).map(x=>x.student_id)}if(ids.length){const {error:a}=await supabase.from("material_assignments").insert(ids.map(student_id=>({material_id:material.id,student_id})));if(a){await supabase.from("materials").delete().eq("id",material.id);redirect(`/teacher/${section}/new?error=assign`)}}}
 await supabase.from("audit_logs").insert({actor_id:user.id,actor_role:"teacher",action:"material.created",entity_type:input.contentKind,entity_id:material.id});revalidatePath(`/teacher/${section}`);revalidatePath("/student/teachers");redirect(`/teacher/${section}?created=1`);
}

export async function updateMaterialBook(formData:FormData){
 const supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/auth/teacher/login");
 const materialKey=z.string().uuid().safeParse(formData.get("materialId")),target=await requireTeacherEducationTarget(),parsed=schema.safeParse({...Object.fromEntries(formData),contentKind:formData.get("contentKind")||"material_book",...target,studentIds:formData.getAll("studentIds").map(String)}),kind=formData.get("contentKind")==="study_note"?"study_note":"material_book",section=kind==="study_note"?"study-notes":"materials";
 if(!materialKey.success||!parsed.success)redirect(`/teacher/${section}/${String(formData.get("materialId"))}/edit?error=invalid`);const input=parsed.data;
 let updateQuery=supabase.from("materials").update({title:input.title,description:input.description||null,material_type:input.materialType,external_drive_url:input.externalUrl,cover_image_url:input.coverImageUrl||null,available_from:input.availableFrom?new Date(input.availableFrom).toISOString():null,available_until:input.availableUntil?new Date(input.availableUntil).toISOString():null,status:input.publish==="on"?"published":"draft",updated_at:new Date().toISOString()}).eq("id",materialKey.data).eq("teacher_id",user.id).eq("resource_kind",kind).eq("education_system",target.educationSystem);updateQuery=target.educationSystem==="american"?updateQuery.eq("american_category",target.americanCategory):updateQuery.eq("national_grade",target.nationalGrade);const {data:material,error}=await updateQuery.select("id").single();
 if(error||!material)redirect(`/teacher/${section}/${materialKey.data}/edit?error=update`);
 let ids=input.studentIds;if(input.assignAll==="on"){const {data:e}=await supabase.from("teacher_student_enrollments").select("student_id").eq("teacher_id",user.id).eq("status","active").or(`access_expires_at.is.null,access_expires_at.gt.${new Date().toISOString()}`);ids=(e??[]).map(x=>x.student_id)}
 const {data:existing}=await supabase.from("material_assignments").select("student_id").eq("material_id",material.id),existingIds=(existing??[]).map(a=>a.student_id),removed=existingIds.filter(id=>!ids.includes(id));
 if(removed.length)await supabase.from("material_assignments").update({revoked_at:new Date().toISOString()}).eq("material_id",material.id).in("student_id",removed);
 if(ids.length){const {error:assignmentError}=await supabase.from("material_assignments").upsert(ids.map(student_id=>({material_id:material.id,student_id,revoked_at:input.publish==="on"?null:new Date().toISOString()})),{onConflict:"material_id,student_id"});if(assignmentError)redirect(`/teacher/${section}/${material.id}/edit?error=assign`)}
 if(input.publish!=="on")await supabase.from("material_assignments").update({revoked_at:new Date().toISOString()}).eq("material_id",material.id);
 await supabase.from("audit_logs").insert({actor_id:user.id,actor_role:"teacher",action:"material.updated",entity_type:kind,entity_id:material.id});revalidatePath(`/teacher/${section}`);revalidatePath("/student/teachers");redirect(`/teacher/${section}?updated=1`);
}

export async function toggleMaterialVisibility(formData:FormData){
 const supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/auth/teacher/login");
 const id=z.string().uuid().safeParse(formData.get("materialId")),kind=formData.get("contentKind")==="study_note"?"study_note":"material_book",section=kind==="study_note"?"study-notes":"materials",show=formData.get("show")==="true";if(!id.success)redirect(`/teacher/${section}?error=invalid`);const target=await requireTeacherEducationTarget();
 let visibilityQuery=supabase.from("materials").update({status:show?"published":"archived",updated_at:new Date().toISOString()}).eq("id",id.data).eq("teacher_id",user.id).eq("resource_kind",kind).eq("education_system",target.educationSystem);visibilityQuery=target.educationSystem==="american"?visibilityQuery.eq("american_category",target.americanCategory):visibilityQuery.eq("national_grade",target.nationalGrade);const {data,error}=await visibilityQuery.select("id").single();if(error||!data)redirect(`/teacher/${section}?error=visibility`);
 await supabase.from("audit_logs").insert({actor_id:user.id,actor_role:"teacher",action:show?"material.shown":"material.hidden",entity_type:kind,entity_id:id.data});revalidatePath(`/teacher/${section}`);revalidatePath("/student/teachers");redirect(`/teacher/${section}?visibility=1`);
}
