import Link from "next/link";
import {ArrowLeft,GraduationCap,KeyRound,Search} from "lucide-react";
import {redirect} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {createAdminClient} from "@/lib/supabase/admin";
import {findStudentForPasswordReset,resetStudentPassword} from "@/features/students/actions";

const errors:Record<string,string>={"invalid-id":"Enter a valid 14-digit National ID.","not-found":"No student account was found for that National ID.","invalid-password":"Use 8–72 characters and make sure both passwords match.",account:"The password could not be updated."};
export default async function StudentPasswordPage({searchParams}:{searchParams:Promise<{studentId?:string;error?:string;updated?:string}>}){
 const query=await searchParams,supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/auth/admin/login");const {data:adminProfile}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(adminProfile?.role!=="admin")redirect("/");
 let student:{id:string;full_name:string}|null=null;if(query.studentId){const {data}=await createAdminClient().from("profiles").select("id,full_name").eq("id",query.studentId).eq("role","student").maybeSingle();student=data}
 return <main className="app-frame"><aside><Link href="/" className="brand"><span className="brand-mark"><GraduationCap/></span>Academy</Link><nav><Link className="active" href="/admin/students">Students</Link><Link href="/admin/dashboard">Dashboard</Link></nav></aside><section className="app-content form-page"><Link className="back-link" href="/admin/students"><ArrowLeft size={16}/>Back to students</Link><header><div><small>Admin workspace</small><h1>Change student password</h1><p>Find the student securely using their National ID.</p></div></header>{query.error&&<p className="form-error" role="alert">{errors[query.error]??errors.account}</p>}{query.updated&&<p className="form-success">The student password was changed successfully.</p>}<form action={findStudentForPasswordReset} className="panel teacher-form student-password-search"><div className="field"><label htmlFor="nationalId">Student National ID</label><input id="nationalId" name="nationalId" inputMode="numeric" pattern="[0-9٠-٩]{14}" minLength={14} maxLength={14} autoComplete="off" required/><small>Enter exactly 14 digits.</small></div><button className="button" type="submit"><Search size={18}/>Find student</button></form>{student&&<form action={resetStudentPassword} className="panel teacher-form"><input type="hidden" name="studentId" value={student.id}/><div className="password-student"><span><KeyRound/></span><div><small>Student account</small><h2>{student.full_name}</h2></div></div><div className="form-grid"><div className="field"><label htmlFor="password">New password</label><input id="password" name="password" type="password" minLength={8} maxLength={72} autoComplete="new-password" required/></div><div className="field"><label htmlFor="confirmPassword">Confirm new password</label><input id="confirmPassword" name="confirmPassword" type="password" minLength={8} maxLength={72} autoComplete="new-password" required/></div></div><div className="form-actions"><Link className="button secondary" href="/admin/students/password">Search again</Link><button className="button" type="submit">Change password</button></div></form>}</section></main>;
}
