import Link from "next/link";
import {redirect} from "next/navigation";
import {ArrowLeft} from "lucide-react";
import {createClient} from "@/lib/supabase/server";
import {updateExistingExam} from "@/features/exams/actions";
import {QuestionImageUpload} from "@/components/question-image-upload";
function localValue(value:string|null){if(!value)return "";return new Intl.DateTimeFormat("sv-SE",{timeZone:"Africa/Cairo",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(value)).replace(" ","T")}
export default async function EditExam({params,searchParams}:{params:Promise<{examId:string}>;searchParams:Promise<{error?:string}>}){
 const {examId}=await params,query=await searchParams,supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/auth/teacher/login");
 const {data:exam}=await supabase.from("exams").select("id,title,description,instructions,duration_minutes,starts_at,ends_at,status,max_attempts,randomize_questions,randomize_choices,published_version_id").eq("id",examId).eq("teacher_id",user.id).single();if(!exam)redirect("/teacher/exams");
 const {data:questions}=await supabase.from("questions").select("id,text,image_url,points,position,question_choices(id,text,is_correct,position)").eq("exam_id",examId).order("position"),{data:latest}=exam.published_version_id?await supabase.from("exam_versions").select("passing_score").eq("id",exam.published_version_id).maybeSingle():{data:null};
 return <main className="app-content exam-page"><Link className="back-link" href="/teacher/exams"><ArrowLeft/>Back to exams</Link><header><div><small>Teacher workspace</small><h1>Edit exam</h1><p>Publishing changes creates a new immutable version for future attempts.</p></div></header>{query.error&&<p className="form-error">The exam could not be updated. Check every question and correct answer.</p>}<form action={updateExistingExam} className="exam-builder"><input type="hidden" name="examId" value={exam.id}/><section className="panel form-grid"><div className="field"><label>Title</label><input name="title" defaultValue={exam.title} required/></div><div className="field"><label>Duration</label><input name="durationMinutes" type="number" defaultValue={exam.duration_minutes} min={1} max={600}/></div><div className="field full"><label>Description</label><textarea name="description" defaultValue={exam.description??""}/></div><div className="field full"><label>Instructions</label><textarea name="instructions" defaultValue={exam.instructions??""}/></div><div className="field"><label>Starts at</label><input name="startsAt" type="datetime-local" defaultValue={localValue(exam.starts_at)}/></div><div className="field"><label>Ends at</label><input name="endsAt" type="datetime-local" defaultValue={localValue(exam.ends_at)}/></div><div className="field"><label>Maximum attempts</label><input name="maxAttempts" type="number" defaultValue={exam.max_attempts} min={1} max={20}/></div><div className="field"><label>Passing score</label><input name="passingScore" type="number" step=".01" defaultValue={latest?.passing_score??""}/></div><label className="check"><input name="randomizeQuestions" type="checkbox" defaultChecked={exam.randomize_questions}/><span><b>Randomize questions</b></span></label><label className="check"><input name="randomizeChoices" type="checkbox" defaultChecked={exam.randomize_choices}/><span><b>Randomize choices</b></span></label><label className="check"><input name="assignAll" type="checkbox" defaultChecked/><span><b>Assign to all active students</b></span></label><label className="check"><input name="publish" type="checkbox" defaultChecked={exam.status==="published"}/><span><b>Published</b></span></label></section>
 {(questions??[]).map((q,i)=><section className="panel question-editor" key={q.id}><div className="question-top"><b>Question {i+1}</b></div><div className="field"><label>Question text</label><textarea name={`q_${q.id}_text`} defaultValue={q.text} required/></div><div className="form-grid"><QuestionImageUpload name={`q_${q.id}_image`} fileName={`q_${q.id}_image_file`} value={q.image_url??""}/><div className="field"><label>Points</label><input name={`q_${q.id}_points`} type="number" step=".01" defaultValue={q.points}/></div></div><div className="choices">{q.question_choices.sort((a,b)=>a.position-b.position).map(c=><div className="choice-row" key={c.id}><input name={`c_${c.id}_text`} defaultValue={c.text} required/><label><input name={`c_${c.id}_correct`} type="checkbox" defaultChecked={c.is_correct}/>Correct</label></div>)}</div></section>)}
 <div className="builder-actions"><Link className="button secondary" href="/teacher/exams">Cancel</Link><button className="button" type="submit">Save changes</button></div></form></main>
}
