import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowLeft,FileText,Layers3 } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { ExamBuilder } from "@/features/exams/exam-builder";
import {requireTeacherEducationTarget} from "@/lib/teacher-education-context";
const messages:Record<string,string>={invalid:"The exam data was incomplete. Please try again.","invalid-title":"Enter an exam title containing between 3 and 200 characters.","invalid-description":"The description must contain no more than 2,000 characters.","invalid-instructions":"The instructions must contain no more than 5,000 characters.","invalid-durationMinutes":"Enter a duration between 1 and 600 minutes.","invalid-maxAttempts":"Enter maximum attempts between 1 and 20.","invalid-dates":"The end date and time must be later than the start date and time.","invalid-environment":"Select a valid teaching environment before creating the exam.","invalid-question-text":"Every question needs text containing no more than 5,000 characters.","invalid-question-image":"One question image is invalid. Remove it and upload a JPG, PNG, WebP, or GIF again.","invalid-question-points":"Every question needs a positive point value and question number.","invalid-choices":"Every question needs at least two choices and one correct answer.","invalid-studentIds":"One selected student is invalid. Refresh the page and select students again.",migration:"The Exams database migration is not installed. Apply the latest Supabase migrations.",questions:"Every question needs at least two choices and one correct answer.",students:"One or more selected students no longer have active access.",image:"An exam image could not be uploaded. Use JPG, PNG, WebP, or GIF up to 3 MB.","teacher-profile":"Your teacher profile is incomplete. Ask the administrator to recreate or repair it.",create:"The database could not create this exam. Apply the latest Supabase migrations and try again."};
export default async function NewExam({searchParams}:{searchParams:Promise<{error?:string;type?:string}>}){
 const query=await searchParams,supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)redirect("/auth/teacher/login");
 const {data:p}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(p?.role!=="teacher")redirect("/");
 const target=await requireTeacherEducationTarget(),est=target.educationSystem==="american"&&target.americanCategory==="est";
 if(est&&query.type!=="passage")return <main className="app-content exam-page"><Link className="back-link" href="/teacher/exams"><ArrowLeft/>Back to exams</Link><header><div><small>EST workspace</small><h1>Choose exam type</h1><p>Select how this EST assessment should be structured.</p></div></header><section className="exam-type-grid"><Link className="panel exam-type-card" href="/teacher/exams/new?type=passage"><FileText/><div><span>Passage Based</span><h2>Standard exam</h2><p>Use the current exam builder, timer, grading, attempts, and results workflow.</p></div></Link><Link className="panel exam-type-card mock" href="/teacher/exams/new/mock"><Layers3/><div><span>Mock Exam</span><h2>Three independent modules</h2><p>Create the container first, then build and publish each module separately.</p></div></Link></section></main>;
 const {data:enrollments}=await supabase.from("teacher_student_enrollments").select("student_id").eq("teacher_id",user.id).eq("status","active").or(`access_expires_at.is.null,access_expires_at.gt.${new Date().toISOString()}`);
 const ids=(enrollments??[]).map(x=>x.student_id),{data:profiles}=ids.length?await supabase.from("profiles").select("id,full_name").in("id",ids):{data:[]};
 return <main className="app-content exam-page"><Link className="back-link" href="/teacher/exams"><ArrowLeft/>Back to exams</Link><header><div><small>Teacher workspace</small><h1>Create exam</h1><p>Build a timed, versioned assessment with exact-set scoring.</p></div></header>{query.error&&<p className="form-error" role="alert">{messages[query.error]??messages.create}</p>}<ExamBuilder students={(profiles??[]).map(x=>({id:x.id,name:x.full_name}))}/></main>;
}
